name: build
on:
  push:
    branches:
      - main

jobs:
  call-dispatch:
        uses: Garvitsh003/trial/.github/workflows/reusable.yml@garvit_testing
        with:
          branch: garvit_testing
